# Stage 1 - Build
FROM node:lts-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2 - Serve
FROM nginx:alpine
COPY config/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/preguntados-de-cero/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
