services:
  backend:
    build: "backend/preguntados-de-cero"
    ports:
      - "8080:8080"
    env_file:
      - .env.prod.backend
    depends_on:
      - sql
  sql:
    container_name: "sql_preguntados-de-cero"
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.prod.db