services:
  backend:
    build: "backend/preguntados-de-cero"
    ports:
      - "8080:8080"
    env_file:
      - .env.prod.backend
    depends_on:
      - sql
  sql:
    image: postgres:17-bookworm
    ports:
      - "5433:5432"
    env_file:
      - .env.prod.db